version: "3.1"

services:

  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    restart: always
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    networks:
    - zabbix-net

  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:alpine-5.2-latest
    restart: unless-stopped
    networks:
    - zabbix-net

  zabbix-server-mysql:
    container_name: zabbix-server-mysql
    image: zabbix/zabbix-server-mysql:5.2-ubuntu-latest
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    networks:
    - zabbix-net
    ports:
    - 10051:10051

  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:5.2-ubuntu-latest
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server-mysql
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    networks:
    - zabbix-net
    ports:
    - 80:8080

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
